name: Test Lunch-Me app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FLUTTER_VERSION: "2.8.1"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: $
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter -j, --concurrency=1
